name: Connect OpenVPN

on: workflow_dispatch

jobs:
  connect-open-vpn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN
        run: sudo apt-get install openvpn
      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: "10.8.0.1"
          FILE_OVPN: ".github/vpn/config.ovpn"
          TLS_KEY: ${{ secrets.TLS_KEY_ENCRYPTED }}
        env:
          CA_CRT: ${{ secrets.CA_CRT_ENCRYPTED}}
          USER_CRT: ${{ secrets.USER_CRT_ENCRYPTED }}
          USER_KEY: ${{ secrets.USER_KEY_ENCRYPTED }}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      - name: Setup SSH
        run: |
          sudo apt-get update
          sudo apt-get install sshpass
      - name: Connect Server
        run: |
          /usr/bin/sshpass -p "${{ secrets.VPN_PASSWORD }}" ssh ${{ secrets.VPN_USER }}@${{ secrets.VPN_HOST }} "cd ~/workspace/social-generator && mkdir test-gha"

      - name: kill vpn
        if: always()
        run: sudo killall openvpn
